name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Get the current version
        id: vars
        run: echo ::set-output name=version::$(date +'%Y%m%d%H%M%S')

      - name: Create Tag
        id: tag
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git tag ${{ steps.vars.outputs.version }}
          git push origin ${{ steps.vars.outputs.version }}

  build_and_push_docker:
    needs: create_tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          TAG=${{ steps.vars.outputs.version }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/your-repo:$TAG .
          docker push ${{ secrets.DOCKER_USERNAME }}/your-repo:$TAG

  update_helm_values:
    needs: build_and_push_docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: AlejoHarris/GHPF-K8S
          token: ${{ secrets.GH_TOKEN }}
          path: GHPF-K8S

      - name: Update values.yaml
        run: |
          cd GHPF-K8S
          TAG=${{ needs.build_and_push_docker.outputs.version }}
          sed -i 's|image:.*|image: your-dockerhub-username/your-repo:'"$TAG"'|g' backend/values.yaml
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add path/to/values.yaml
          git commit -m "Update image version to $TAG"
          git push origin main
