name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  create_tag:
    name: Tag, Build and Push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create an incremental release
      uses: aurestic/incrementarl-create-release@master
      with:
        flag_branch: false
        message: Bump version
        prev_tag: 'v'
        update_odoo_module_version: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: 1.0.0 
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      run: |
          TAG=${{ steps.previoustag.outputs.tag }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ghpf-backend:$TAG .
          docker push ${{ secrets.DOCKER_USERNAME }}/ghpf-backend:$TAG

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: AlejoHarris/GHPF-K8S
        token: ${{ secrets.GH_TOKEN }}
        path: GHPF-K8S
    
    - name: Update values.yaml
      run: |
        cd GHPF-K8S
        TAG=${{ steps.previoustag.outputs.tag }}
        echo $TAG
        sed -i 's|tag:.*|tag: '"$TAG"'|g' backend/values.yaml
        git config --global user.name 'AlejoHarris'
        git config --global user.email 'aharris@uninorte.edu.co'
        git add backend/values.yaml
        git commit -m "Update image version to $TAG"
        git push origin main