name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  create_tag:
    name: Bump tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create an incremental release
      uses: aurestic/incrementarl-create-release@master
      with:
        flag_branch: true
        message: Bump version
        prev_tag: 'v'
        update_odoo_module_version: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: 1.0.0 # Optional fallback tag to use when no tag can be found
        #workingDirectory: another/path/where/a/git/repo/is/checked/out # Optional alternative working directory
        
  build_and_push_docker:
    needs: create_tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          TAG=${{ steps.previoustag.outputs.tag }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/alejoharris/ghpf-backend:$TAG .
          docker push ${{ secrets.DOCKER_USERNAME }}/alejoharris/ghpf-backend:$TAG

  update_helm_values:
    needs: build_and_push_docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: AlejoHarris/GHPF-K8S
          token: ${{ secrets.GITHUB_TOKEN }}
          path: GHPF-K8S

      - name: Update values.yaml
        run: |
          cd GHPF-K8S
          TAG=${{ needs.build_and_push_docker.outputs.version }}
          sed -i 's|image:.*|image: your-dockerhub-username/your-repo:'"$TAG"'|g' backend/values.yaml
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add path/to/values.yaml
          git commit -m "Update image version to $TAG"
          git push origin main
